# Generated by Django 4.0.5 on 2022-06-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVTPrimerProyectoApp', '0002_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
